# Generated by Django 3.2.23 on 2023-11-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=30)),
                ('num_guests', models.IntegerField(choices=[(1, 1), (2, 2)])),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[(1, '16:00'), (2, '18:00'), (3, '20:00')], max_length=1)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
