# Generated by Django 3.2.23 on 2023-11-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thehut', '0002_auto_20231109_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='time',
            field=models.CharField(choices=[(1, '16:00'), (2, '18:00'), (3, '20:00')], max_length=5),
        ),
    ]
